version: '3.7'

services:
  telegram:
    build: ./telegram
    #command: python littlebirds.py
    command: python test.py
    env_file: .env.tg
    volumes:
      - ./telegram/:/usr/src/telegram/
    ports:
      - 8000
    stdin_open: true
    tty: true

  db:
    image: postgres:11.2-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
      - POSTGRES_DB=hello_django_dev

  bridge:
    build: ./bridge
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./bridge/:/usr/src/bridge/
    ports:
      - 8000:8000
    environment:
      - DEBUG=1
      - SECRET_KEY=foo
      - SQL_ENGINE=django.db.backends.postgresql
      - SQL_DATABASE=hello_django_dev
      - SQL_USER=hello_django
      - SQL_PASSWORD=hello_django
      - SQL_HOST=db
      - SQL_PORT=5432
      - DATABASE=postgres
    depends_on:
      - db

volumes:
  postgres_data:
